# Generated by Django 3.2.4 on 2021-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choise',
            name='abstained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choise',
            name='protiv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choise',
            name='za',
            field=models.IntegerField(default=0),
        ),
    ]
