# Generated by Django 3.2.4 on 2021-07-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210706_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choise_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.choise'),
            preserve_default=False,
        ),
    ]
