# Generated by Django 3.2.4 on 2021-07-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_choise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choise_id',
        ),
    ]
